import React, { useState } from 'react';
import { Download, History, Send } from 'lucide-react';
import { Button, PageHeader, Section, StatusBadge } from '../../components/UI';

export default function GradeFeedbackPage() {
  const [comment, setComment] = useState('');
  const [messages, setMessages] = useState([{ author: 'Lê Hoàng Nam', initials: 'HN', time: '14/07 · 20:15', text: 'Em làm bài đầy đủ và trình bày rõ ràng. Hãy kiểm tra lại chính tả từ “restaurant” và luyện thêm ngữ điệu ở câu cuối.' }]);
  const send = () => { if (!comment.trim()) return; setMessages([...messages, { author: 'Nguyễn Minh Anh', initials: 'MA', time: 'Vừa xong', text: comment }]); setComment(''); };
  return <>
    <PageHeader eyebrow="ST-06 · ĐIỂM & NHẬN XÉT" title="Write about your daily routine" description="Everyday English A2 · Writing" breadcrumbs="Bài tập / Write about your daily routine / Kết quả" actions={<StatusBadge status="Returned" />} />
    <section className="grade-hero"><div><span>Điểm của bạn</span><strong>8.5</strong><small>/ 10</small></div><div><span>Điểm lớp trung bình</span><strong>7.8</strong></div><div><span>Đã trả điểm</span><strong>14/07/2026</strong></div><Button variant="light" icon={Download}>Tải bài đã chấm</Button></section>
    <div className="dashboard-grid dashboard-grid--wide"><Section title="Nhận xét của Mentor"><div className="mentor-feedback"><span className="avatar">HN</span><div><strong>Lê Hoàng Nam</strong><p>Em làm bài đầy đủ và trình bày rõ ràng. Bố cục tốt, sử dụng đúng thì hiện tại đơn. Hãy kiểm tra lại chính tả từ <mark>restaurant</mark> và luyện thêm cách nối câu bằng then, after that.</p></div></div><div className="rubric-result"><div><span>Nội dung</span><strong>3.5 / 4</strong><i style={{ width: '87.5%' }} /></div><div><span>Từ vựng</span><strong>2.0 / 2</strong><i style={{ width: '100%' }} /></div><div><span>Ngữ pháp</span><strong>2.0 / 2.5</strong><i style={{ width: '80%' }} /></div><div><span>Trình bày</span><strong>1.0 / 1.5</strong><i style={{ width: '67%' }} /></div></div></Section><Section title="Lịch sử điểm" actions={<History size={19} />}><div className="grade-history"><div><span>14/07 · 20:15</span><strong>8.5/10</strong><small>Điểm hiện tại</small></div><div><span>14/07 · 19:42</span><strong>8.0/10</strong><small>Đã chỉnh sửa · Lý do: cộng rubric nội dung</small></div></div></Section></div>
    <Section title="Trao đổi với Mentor" description="Đặt câu hỏi trực tiếp về bài làm hoặc nhận xét."><div className="comment-thread">{messages.map((m, i) => <div key={i} className={m.author === 'Nguyễn Minh Anh' ? 'is-self' : ''}><span className="avatar avatar--small">{m.initials}</span><div><strong>{m.author}<small>{m.time}</small></strong><p>{m.text}</p></div></div>)}</div><div className="comment-box"><textarea aria-label="Câu hỏi hoặc phản hồi cho Mentor" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Viết câu hỏi hoặc phản hồi…" /><Button icon={Send} onClick={send}>Gửi</Button></div></Section>
  </>;
}
