import React, { useState } from 'react';
import { Download, History, Send } from 'lucide-react';
import { Button, PageHeader, Section, StatusBadge } from '../../components/UI';

export default function GradeFeedbackPage() {
  const [comment, setComment] = useState('');
  const [messages, setMessages] = useState([{ author: 'Le Hoang Nam', initials: 'HN', time: '14/07 · 20:15', text: 'You completed the task clearly. Check the spelling of “restaurant” and practise the intonation in your final sentence.' }]);
  const send = () => { if (!comment.trim()) return; setMessages([...messages, { author: 'Nguyen Minh Anh', initials: 'MA', time: 'Just now', text: comment }]); setComment(''); };
  return <>
    <PageHeader eyebrow="ST-06 · SCORE & FEEDBACK" title="Write about your daily routine" description="Everyday English A2 · Writing" breadcrumbs="Assignments / Write about your daily routine / Results" actions={<StatusBadge status="Returned" />} />
    <section className="grade-hero"><div><span>Your score</span><strong>8.5</strong><small>/ 10</small></div><div><span>Class average</span><strong>7.8</strong></div><div><span>Returned on</span><strong>14/07/2026</strong></div><Button variant="light" icon={Download}>Download graded work</Button></section>
    <div className="dashboard-grid dashboard-grid--wide"><Section title="Mentor feedback"><div className="mentor-feedback"><span className="avatar">HN</span><div><strong>Le Hoang Nam</strong><p>You completed the task clearly and used the present simple correctly. Check the spelling of <mark>restaurant</mark> and practise linking ideas with then and after that.</p></div></div><div className="rubric-result"><div><span>Content</span><strong>3.5 / 4</strong><i style={{ width: '87.5%' }} /></div><div><span>Vocabulary</span><strong>2.0 / 2</strong><i style={{ width: '100%' }} /></div><div><span>Grammar</span><strong>2.0 / 2.5</strong><i style={{ width: '80%' }} /></div><div><span>Presentation</span><strong>1.0 / 1.5</strong><i style={{ width: '67%' }} /></div></div></Section><Section title="Score history" actions={<History size={19} />}><div className="grade-history"><div><span>14/07 · 20:15</span><strong>8.5/10</strong><small>Current score</small></div><div><span>14/07 · 19:42</span><strong>8.0/10</strong><small>Edited · Reason: content rubric adjustment</small></div></div></Section></div>
    <Section title="Discuss with your mentor" description="Ask a question about your work or feedback."><div className="comment-thread">{messages.map((m, i) => <div key={i} className={m.author === 'Nguyen Minh Anh' ? 'is-self' : ''}><span className="avatar avatar--small">{m.initials}</span><div><strong>{m.author}<small>{m.time}</small></strong><p>{m.text}</p></div></div>)}</div><div className="comment-box"><textarea aria-label="Question or feedback for your mentor" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Write a question or reply..." /><Button icon={Send} onClick={send}>Send</Button></div></Section>
  </>;
}
