import React, { useState } from 'react';
import { Download, ExternalLink, FileText, PlayCircle } from 'lucide-react';
import { Button, PageHeader, Section, StatusBadge, Tabs, Toast } from '../../components/UI';
import { useStore } from '../../data/store';

export default function SessionsPage() {
  const { data } = useStore(); const [tab, setTab] = useState('upcoming'); const [notice, setNotice] = useState('');
  const current = tab === 'upcoming' ? data.sessions.filter((s) => s.status === 'Upcoming') : data.sessions.filter((s) => s.status !== 'Upcoming');
  const open = (url, message) => { if (url) window.open(url, '_blank', 'noopener,noreferrer'); else { setNotice(message); window.setTimeout(() => setNotice(''), 2500); } };
  return <><PageHeader eyebrow="ST-03 · SESSIONS" title="Sessions and resources" description="Everyday English A2 · Class A2-01" breadcrumbs="My courses / Everyday English A2 / Sessions" /><Tabs items={[{ key: 'upcoming', label: 'Upcoming' }, { key: 'completed', label: 'Completed' }]} active={tab} onChange={setTab} /><Section>{current.length ? <div className="session-list">{current.map((s) => <article key={s.id}><div className="session-list__date"><span>{s.date.split(',')[0]}</span><strong>{s.date.match(/\d+/)?.[0]}</strong><small>JUL</small></div><div className="session-list__content"><div><StatusBadge status={s.status} /><span className="record-code">{s.id}</span></div><h2>{s.title}</h2><p>{s.time} · {s.type}</p><div className="session-list__resources"><button type="button" onClick={() => open(null, 'Student book is ready to download.')}><FileText size={17} />Student book.pdf</button><button type="button" onClick={() => open(null, 'Audio practice is ready to download.')}><PlayCircle size={17} />Audio practice.mp3</button></div></div><div className="session-list__actions">{s.status === 'Upcoming' ? <Button icon={ExternalLink} onClick={() => open(s.meetingUrl, 'The meeting link is not available yet.')}>Join class</Button> : <><Button variant="secondary" icon={PlayCircle} onClick={() => open(s.recordingUrl, 'Recording is not available for this session.')}>Watch recording</Button><Button variant="ghost" icon={Download} onClick={() => open(null, 'Materials download started.')}>Download materials</Button></>}</div></article>)}</div> : <p>No sessions in this view.</p>}</Section>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;
}
