import React, { useState } from 'react';
import { CheckCircle2, ChevronLeft, ChevronRight, Download, Save } from 'lucide-react';
import { Badge, Button, Field, PageHeader, StatusBadge, Toast } from '../../components/UI';
import { submissions } from '../../data/mockData';
import { useStore } from '../../data/store';

export default function GradingPage() {
  const { update } = useStore(); const [items, setItems] = useState(submissions); const [selected, setSelected] = useState(0); const [score, setScore] = useState(submissions[0].score || ''); const [feedback, setFeedback] = useState('The work is complete and clearly presented. Check the spelling of restaurant.'); const [saved, setSaved] = useState(false); const current = items[selected];
  const select = (index) => { setSelected(index); setScore(items[index].score || ''); };
  const save = (returned = false) => { const next = items.map((item, index) => index === selected ? { ...item, score, status: returned ? 'Returned' : item.status } : item); setItems(next); update('submissions', next); setSaved(true); window.setTimeout(() => setSaved(false), 2000); };
  return <><PageHeader eyebrow="ME-08 · GRADING" title="Unit 5 vocabulary worksheet" description="Everyday English A2 · 24 submissions · Max score 10" /><div className="grading-layout"><aside className="grading-queue"><div className="grading-queue__header"><strong>Submission queue</strong><select aria-label="Filter submission status"><option>All statuses</option><option>Submitted</option><option>Returned</option></select></div><div className="grading-queue__list">{items.map((s, index) => <button type="button" key={s.id || s.student} className={selected === index ? 'is-active' : ''} onClick={() => select(index)}><span className="avatar avatar--small">{s.student.split(' ').slice(-2).map((x) => x[0]).join('')}</span><span><strong>{s.student}</strong><small>{s.submittedAt}</small></span><StatusBadge status={s.status} /></button>)}</div></aside><section className="grading-workspace"><div className="grading-workspace__bar"><div><strong>{current.student}</strong><span>{current.file}</span></div><Button variant="secondary" size="sm" icon={Download} onClick={() => setSaved(true)}>Download file</Button></div><div className="submission-preview"><div className="paper-preview"><span>UNIT 5 — VOCABULARY WORKSHEET</span><h3>Places in town</h3><p>1. You can borrow books at the <u>library</u>.</p><p>2. You can buy medicine at the <u>pharmacy</u>.</p><p>3. You can catch a bus at the <u>bus station</u>.</p><p>4. My favourite place is the park because it is quiet.</p><div className="paper-preview__footer">Page 1 / 1</div></div></div><div className="grading-panel"><div className="score-field"><label htmlFor="score">Score</label><div><input id="score" value={score} onChange={(e) => setScore(e.target.value)} inputMode="decimal" /><span>/ 10</span></div></div><Field label="Feedback"><textarea rows="5" value={feedback} onChange={(e) => setFeedback(e.target.value)} /></Field><div className="rubric"><strong>Quick rubric</strong><label><input type="checkbox" defaultChecked />Correct vocabulary</label><label><input type="checkbox" defaultChecked />All requirements completed</label><label><input type="checkbox" />No spelling errors</label></div><div className="grading-panel__actions"><Button variant="secondary" icon={Save} onClick={() => save()}>Save draft</Button><Button icon={CheckCircle2} disabled={!score || !feedback.trim()} onClick={() => save(true)}>Return grade</Button></div><div className="grading-nav"><button type="button" disabled={selected === 0} onClick={() => select(selected - 1)}><ChevronLeft size={17} />Previous</button><Badge tone="info">{selected + 1} / {items.length}</Badge><button type="button" disabled={selected === items.length - 1} onClick={() => select(selected + 1)}>Next<ChevronRight size={17} /></button></div></div></section></div>{saved ? <Toast>Grading changes saved.</Toast> : null}</>;
}
