import React, { useState } from 'react';
import { ClipboardCheck, ExternalLink, Link2, Save, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, Field, PageHeader, Section, Toast, UploadZone } from '../../components/UI';

export default function SessionDetailPage() {
  const navigate = useNavigate(); const [saved, setSaved] = useState(false); const [files, setFiles] = useState(['Unit 6 — Student book.pdf', 'Giving directions — Audio.mp3']); const feedback = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <><PageHeader eyebrow="ME-04 · SESSION MANAGEMENT" title="Unit 6 · Giving directions" description="Session 12 · Thursday, 16/07/2026 · 19:00–20:30" breadcrumbs="Class A2-01 / Session / SS-12" actions={<><Button variant="secondary" icon={ClipboardCheck} onClick={() => navigate('/mentor/attendance')}>Attendance</Button><Button icon={ExternalLink} onClick={() => window.open('https://meet.google.com/hope-a201', '_blank', 'noopener,noreferrer')}>Join class</Button></>} /><div className="dashboard-grid dashboard-grid--wide"><Section title="Session information"><div className="form-stack"><Field label="Topic"><input defaultValue="Unit 6 · Giving directions" /></Field><Field label="Meeting link"><div className="input-with-action"><input defaultValue="https://meet.google.com/hope-a201" /><Button variant="secondary" icon={Link2} onClick={feedback}>Check link</Button></div></Field><Field label="Learning goals"><textarea rows="5" defaultValue="Students can ask for and give directions using basic phrases." /></Field><Button icon={Save} onClick={feedback}>Save changes</Button></div></Section><Section title="Session materials" actions={<Button variant="ghost" icon={Upload} onClick={feedback}>Choose from library</Button>}><div className="file-list">{files.map((file) => <div key={file}><span>{file.endsWith('.pdf') ? 'PDF' : 'MP3'}</span><p><strong>{file}</strong><small>Shared with students</small></p><button type="button" onClick={() => setFiles((items) => items.filter((item) => item !== file))}>Remove</button></div>)}</div><UploadZone title="Add material" onChange={feedback} /></Section></div><Section title="After the session" description="Recording and notes become visible to students after completion."><div className="form-grid"><Field label="Recording link"><input placeholder="https://drive.google.com/…" /></Field><Field label="Session notes"><textarea rows="4" placeholder="What was taught, follow-up points and homework…" /></Field></div><div className="form-actions"><Button variant="secondary" onClick={feedback}>Save draft</Button><Button onClick={feedback}>Complete session</Button></div></Section>{saved ? <Toast>Session changes saved.</Toast> : null}</>;
}
