import React, { useState } from 'react';
import { ArrowLeft, Send } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, Field, InlineNotice, PageHeader, Section, Toast } from '../../components/UI';
import { useStore } from '../../data/store';

export default function CreateEditUserPage() {
  const navigate = useNavigate(); const { update } = useStore(); const [form, setForm] = useState({ name: '', email: '', id: '', role: 'Student', phone: '', status: 'Active' }); const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.email.trim() || !form.id.trim()) { setError('Name, email and user ID are required.'); return; } update('users', (items) => [{ ...form, lastLogin: 'Never logged in' }, ...items]); setSaved(true); window.setTimeout(() => navigate('/admin/users'), 700); };
  return <><PageHeader eyebrow="AD-03 · USER FORM" title="Create user" description="The account will receive a welcome email and first-login setup link." actions={<Button variant="ghost" icon={ArrowLeft} onClick={() => navigate('/admin/users')}>Back to users</Button>} /><Section className="form-section"><form className="form-grid" onSubmit={submit}><Field label="Full name" required><input value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="Enter full name" /></Field><Field label="Email" required><input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} placeholder="name@hope.edu.vn" /></Field><Field label="User ID" required><input value={form.id} onChange={(e) => set('id', e.target.value)} placeholder="HS-0000" /></Field><Field label="Role" required><select value={form.role} onChange={(e) => set('role', e.target.value)}><option>Student</option><option>Mentor</option><option>Coordinator</option><option>Admin</option></select></Field><Field label="Phone"><input value={form.phone} onChange={(e) => set('phone', e.target.value)} placeholder="090 000 0000" /></Field><Field label="Initial status"><select value={form.status} onChange={(e) => set('status', e.target.value)}><option>Active</option><option>Pending</option></select></Field><div className="form-grid__full"><InlineNotice title="Welcome email">HELIX sends a first-login link valid for 72 hours. Temporary passwords are never emailed.</InlineNotice></div>{error ? <div className="form-grid__full"><InlineNotice tone="danger" title="Please fix the form">{error}</InlineNotice></div> : null}<div className="form-actions form-grid__full"><Button variant="secondary" onClick={() => navigate('/admin/users')}>Cancel</Button><Button type="submit" icon={Send} disabled={saved}>Create and send invite</Button></div></form></Section>{saved ? <Toast>User created successfully.</Toast> : null}</>;
}
