import React, { useState } from 'react';
import { Save } from 'lucide-react';
import { Button, Field, InlineNotice, PageHeader, Section, Tabs, Toast } from '../../components/UI';

export default function SystemConfigurationPage() {
  const [tab, setTab] = useState('email');
  const [saved, setSaved] = useState(false);
  const save = () => { setSaved(true); setTimeout(() => setSaved(false), 2500); };
  return <>
    <PageHeader eyebrow="AD-05 · ADMINISTRATION" title="System configuration" description="Configure email, files, notifications, features, and attendance rules." actions={<Button icon={Save} onClick={save}>Save configuration</Button>} />
    <Tabs items={[{ key: 'email', label: 'Email' }, { key: 'file', label: 'File uploads' }, { key: 'notification', label: 'Notifications' }, { key: 'feature', label: 'Features' }, { key: 'attendance', label: 'Attendance' }]} active={tab} onChange={setTab} />
    {tab === 'email' ? <Section title="Email delivery"><div className="form-grid"><Field label="Sender name"><input defaultValue="HELIX · Hope School" /></Field><Field label="Sender email"><input defaultValue="no-reply@hope.edu.vn" /></Field><Field label="Reply-to"><input defaultValue="support@hope.edu.vn" /></Field><Field label="First Login link lifetime"><div className="input-suffix"><input type="number" defaultValue="72" /><span>hours</span></div></Field></div></Section> : tab === 'file' ? <Section title="File limits"><div className="form-grid"><Field label="Maximum file size"><div className="input-suffix"><input type="number" defaultValue="50" /><span>MB</span></div></Field><Field label="Allowed file types"><input defaultValue="pdf, docx, pptx, xlsx, mp3, mp4, zip" /></Field><Field label="Storage per user"><div className="input-suffix"><input type="number" defaultValue="2" /><span>GB</span></div></Field></div></Section> : tab === 'notification' ? <Section title="Notification channels"><div className="settings-list"><label><span><strong>In-app notifications</strong><small>Always enabled for important events.</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Assignment emails</strong><small>Send on publication, near the deadline, and after grading.</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Schedule emails</strong><small>Send 24 hours before class and whenever the schedule changes.</small></span><input type="checkbox" defaultChecked /></label></div></Section> : tab === 'feature' ? <Section title="Feature flags"><InlineNotice title="MVP scope">AI features follow the current Phase 1 release plan.</InlineNotice><div className="settings-list"><label><span><strong>AI learning assistant</strong><small>Phase 2 · Not released</small></span><input type="checkbox" disabled /></label><label><span><strong>Automated feedback</strong><small>Phase 2 · Not released</small></span><input type="checkbox" disabled /></label><label><span><strong>Comment thread</strong><small>Allow discussion under graded submissions.</small></span><input type="checkbox" defaultChecked /></label></div></Section> : <Section title="Attendance rules"><div className="form-grid"><Field label="Editing grace period"><div className="input-suffix"><input type="number" defaultValue="24" /><span>hours</span></div></Field><Field label="Default status"><select defaultValue="Absent"><option>Absent</option><option>Present</option></select></Field><Field label="Allow Mark All Present"><select defaultValue="yes"><option value="yes">Yes</option><option value="no">No</option></select></Field></div></Section>}
    {saved ? <Toast>System configuration saved.</Toast> : null}
  </>;
}
