import React, { useState } from 'react';
import { Save } from 'lucide-react';
import { Button, Field, InlineNotice, PageHeader, Section, Tabs, Toast } from '../../components/UI';

export default function SystemConfigurationPage() {
  const [tab, setTab] = useState('email');
  const [saved, setSaved] = useState(false);
  const save = () => { setSaved(true); setTimeout(() => setSaved(false), 2500); };
  return <>
    <PageHeader eyebrow="AD-05 · QUẢN TRỊ" title="Cấu hình hệ thống" description="Thiết lập email, tệp, thông báo, tính năng và quy tắc điểm danh." actions={<Button icon={Save} onClick={save}>Lưu cấu hình</Button>} />
    <Tabs items={[{ key: 'email', label: 'Email' }, { key: 'file', label: 'Tệp tải lên' }, { key: 'notification', label: 'Thông báo' }, { key: 'feature', label: 'Tính năng' }, { key: 'attendance', label: 'Điểm danh' }]} active={tab} onChange={setTab} />
    {tab === 'email' ? <Section title="Cấu hình gửi email"><div className="form-grid"><Field label="Tên người gửi"><input defaultValue="HELIX · Hope School" /></Field><Field label="Email người gửi"><input defaultValue="no-reply@hope.edu.vn" /></Field><Field label="Reply-to"><input defaultValue="support@hope.edu.vn" /></Field><Field label="Thời hạn link First Login"><div className="input-suffix"><input type="number" defaultValue="72" /><span>giờ</span></div></Field></div></Section> : tab === 'file' ? <Section title="Giới hạn tệp"><div className="form-grid"><Field label="Dung lượng tối đa mỗi tệp"><div className="input-suffix"><input type="number" defaultValue="50" /><span>MB</span></div></Field><Field label="Loại tệp cho phép"><input defaultValue="pdf, docx, pptx, xlsx, mp3, mp4, zip" /></Field><Field label="Dung lượng mỗi người dùng"><div className="input-suffix"><input type="number" defaultValue="2" /><span>GB</span></div></Field></div></Section> : tab === 'notification' ? <Section title="Kênh thông báo"><div className="settings-list"><label><span><strong>Thông báo trong ứng dụng</strong><small>Luôn bật cho sự kiện quan trọng.</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Email bài tập</strong><small>Gửi khi publish, gần deadline và trả điểm.</small></span><input type="checkbox" defaultChecked /></label><label><span><strong>Email lịch học</strong><small>Nhắc trước 24 giờ và khi lịch thay đổi.</small></span><input type="checkbox" defaultChecked /></label></div></Section> : tab === 'feature' ? <Section title="Feature flags"><InlineNotice title="Phạm vi MVP">Các tính năng AI đang tắt theo tài liệu Phase 1.</InlineNotice><div className="settings-list"><label><span><strong>AI learning assistant</strong><small>Phase 2 · Chưa phát hành</small></span><input type="checkbox" disabled /></label><label><span><strong>Nhận xét tự động</strong><small>Phase 2 · Chưa phát hành</small></span><input type="checkbox" disabled /></label><label><span><strong>Comment thread</strong><small>Cho phép trao đổi dưới bài đã chấm.</small></span><input type="checkbox" defaultChecked /></label></div></Section> : <Section title="Quy tắc điểm danh"><div className="form-grid"><Field label="Grace period chỉnh sửa"><div className="input-suffix"><input type="number" defaultValue="24" /><span>giờ</span></div></Field><Field label="Trạng thái mặc định"><select defaultValue="Absent"><option>Absent</option><option>Present</option></select></Field><Field label="Cho phép Mark All Present"><select defaultValue="yes"><option value="yes">Có</option><option value="no">Không</option></select></Field></div></Section>}
    {saved ? <Toast>Đã lưu cấu hình hệ thống.</Toast> : null}
  </>;
}
