import React, { useMemo, useState } from 'react';
import { Download, MoreHorizontal, Upload, UserPlus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, DataTable, PageHeader, SearchField, Section, StatusBadge, Tabs, Toast } from '../../components/UI';
import { useStore } from '../../data/store';

export default function UserManagementPage() {
  const navigate = useNavigate(); const { data, update } = useStore(); const [query, setQuery] = useState(''); const [tab, setTab] = useState('All'); const [notice, setNotice] = useState('');
  const rows = useMemo(() => data.users.filter((r) => (tab === 'All' || r.status === tab) && `${r.name} ${r.email} ${r.id}`.toLowerCase().includes(query.toLowerCase())), [data.users, query, tab]);
  const exportData = () => { const blob = new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'helix-users.json'; link.click(); URL.revokeObjectURL(url); };
  const columns = [{ key: 'id', label: 'ID' }, { key: 'name', label: 'Name', render: (r) => <div className="cell-primary"><strong>{r.name}</strong><small>{r.email}</small></div> }, { key: 'role', label: 'Role' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }, { key: 'lastLogin', label: 'Last login' }, { key: 'actions', label: '', render: (r) => <button type="button" className="icon-button" aria-label={`Toggle ${r.name}`} onClick={() => { update('users', (items) => items.map((u) => u.id === r.id ? { ...u, status: u.status === 'Inactive' ? 'Active' : 'Inactive' } : u)); setNotice('User status updated.'); }}><MoreHorizontal size={18} /></button> }];
  return <><PageHeader eyebrow="AD-02 · ADMIN" title="User management" description="Create, assign roles, activate and manage account lifecycle." actions={<><Button variant="secondary" icon={Upload} onClick={() => navigate('/admin/users/import')}>Import CSV</Button><Button icon={UserPlus} onClick={() => navigate('/admin/users/new')}>Create user</Button></>} /><Section><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search by name, email or ID…" /><select aria-label="Filter role"><option>All roles</option><option>Student</option><option>Mentor</option><option>Coordinator</option><option>Admin</option></select><Button variant="ghost" icon={Download} onClick={exportData}>Export data</Button></div><Tabs items={['All', 'Active', 'Pending', 'Inactive']} active={tab} onChange={setTab} /><DataTable columns={columns} rows={rows} emptyTitle="No users found" emptyText="Try changing your search or filter." /></Section>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;
}
