import React, { useMemo, useState } from 'react';
import { CalendarDays, MoreHorizontal, Plus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button, Field, Modal, PageHeader, Progress, SearchField, Section, StatusBadge, Tabs, Toast } from '../../components/UI';
import { useStore } from '../../data/store';

export default function ProgramsPage() {
  const navigate = useNavigate(); const { data, update } = useStore(); const [query, setQuery] = useState(''); const [tab, setTab] = useState('All'); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [notice, setNotice] = useState('');
  const list = useMemo(() => data.programs.filter((p) => (tab === 'All' || p.status === tab) && p.name.toLowerCase().includes(query.toLowerCase())), [data.programs, query, tab]);
  const create = () => { if (!name.trim()) return; update('programs', (items) => [{ id: `PRG-${Date.now()}`, name, term: 'Summer 2026', courses: 0, classes: 0, students: 0, status: 'Draft', progress: 0 }, ...items]); setName(''); setOpen(false); setNotice('Program created as draft.'); };
  return <><PageHeader eyebrow="CO-02 · COORDINATOR" title="Programs" description="Create and operate the Program → Course → Class structure." actions={<Button icon={Plus} onClick={() => setOpen(true)}>Create program</Button>} /><Section><div className="toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search programs…" /><select aria-label="Academic year"><option>Academic year 2026</option><option>Academic year 2025</option></select></div><Tabs items={['All', 'Active', 'Draft', 'Completed']} active={tab} onChange={setTab} /><div className="program-list">{list.length ? list.map((p) => <article key={p.id}><div className="program-list__main"><div><span className="record-code">{p.id}</span><h3>{p.name}</h3><p><CalendarDays size={15} />{p.term}</p></div><button type="button" className="icon-button" aria-label={`Open ${p.name}`} onClick={() => navigate(`/coordinator/programs/${p.id}`)}><MoreHorizontal size={18} /></button></div><div className="program-list__meta"><div><span>Courses</span><strong>{p.courses}</strong></div><div><span>Classes</span><strong>{p.classes}</strong></div><div><span>Students</span><strong>{p.students}</strong></div><StatusBadge status={p.status} /></div><Progress value={p.progress} label="Program progress" /><div className="program-list__actions"><Button variant="secondary" size="sm" onClick={() => navigate(`/coordinator/programs/${p.id}`)}>Open details</Button><Button variant="ghost" size="sm" onClick={() => navigate('/coordinator/courses')}>Manage courses</Button></div></article>) : <p>No programs found.</p>}</div></Section><Modal open={open} onClose={() => setOpen(false)} title="Create program" description="New programs start as drafts." footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!name.trim()} onClick={create}>Create program</Button></>}><div className="form-grid"><Field label="Program name" required><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Example: English Foundation 2026" /></Field><Field label="School" required><select><option>Hope School Da Nang</option></select></Field><Field label="Start date" required><input type="date" /></Field><Field label="End date" required><input type="date" /></Field><Field label="Description"><textarea rows="4" /></Field></div></Modal>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;
}
