import React, { useMemo, useState } from 'react';
import { ArrowRight, BrainCircuit, Check, ChevronRight, Clock3, Coins, Headphones, Mic2, Play, RefreshCw, Sparkles, Target, Video } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button, Field, PageHeader, Section, StatusBadge, Toast } from '../../components/UI';
import { useStore } from '../../data/store';

const modes = [
  { key: 'listening', label: 'Listening', icon: Headphones, color: 'blue', copy: 'Train your ear with short, adaptive conversations.' },
  { key: 'speaking', label: 'Speaking', icon: Mic2, color: 'orange', copy: 'Speak naturally and get instant pronunciation feedback.' },
  { key: 'reading', label: 'Reading', icon: Target, color: 'green', copy: 'Build speed and accuracy with focused passages.' },
  { key: 'writing', label: 'Writing', icon: BrainCircuit, color: 'purple', copy: 'Write with confidence and learn from every correction.' },
];

function roleFromPath(pathname) { return pathname.split('/')[1] || 'student'; }

export default function ExperienceHubPage({ mode = 'ai' }) {
  const location = useLocation(); const navigate = useNavigate(); const role = roleFromPath(location.pathname); const { data, update } = useStore(); const [activeMode, setActiveMode] = useState('speaking'); const [notice, setNotice] = useState(''); const [running, setRunning] = useState(false); const [meetTitle, setMeetTitle] = useState('');
  const tokenBalance = data.tokens?.balance ?? 120;
  const mistakes = data.aiMistakes || [{ id: 'm1', skill: 'Speaking', title: 'Final consonants', detail: 'worked / walked / watched', count: 3 }, { id: 'm2', skill: 'Grammar', title: 'Past simple questions', detail: 'Did you…? / Were you…?', count: 2 }, { id: 'm3', skill: 'Vocabulary', title: 'Directions and places', detail: 'opposite · between · across', count: 4 }];
  const tests = data.assessments || [{ id: 'placement', title: 'English placement test', kind: 'Placement', duration: '25 min', level: 'A1 → B2', status: 'Not started' }, { id: 'review-a2', title: 'A2 progress check', kind: 'Review', duration: '15 min', level: 'A2', status: 'Ready' }, { id: 'review-speaking', title: 'Speaking confidence check', kind: 'Practice test', duration: '10 min', level: 'Speaking', status: 'Ready' }];
  const startPractice = () => { setRunning(true); update('tokens', (current = { balance: tokenBalance }) => ({ ...current, balance: Math.max(0, (current.balance ?? tokenBalance) - 5), spent: (current.spent || 0) + 5 })); setNotice(`${activeMode} practice started · 5 tokens used.`); window.setTimeout(() => { setRunning(false); navigate('/student/ai/session'); }, 650); };
  const retry = (mistake) => { update('aiMistakes', (items = mistakes) => items.map((item) => item.id === mistake.id ? { ...item, count: Math.max(0, item.count - 1), lastReviewed: 'Just now' } : item)); setNotice(`Reviewing ${mistake.title}.`); };
  const buy = (amount, price) => { update('tokens', (current = { balance: tokenBalance }) => ({ ...current, balance: (current.balance ?? 0) + amount, purchased: (current.purchased || 0) + amount })); setNotice(`${amount} tokens added · payment demo ${price}.`); };
  const createMeet = () => { if (!meetTitle.trim()) return; update('meetings', (items = []) => [{ id: `meet-${Date.now()}`, title: meetTitle, host: role, status: 'Ready', checkIn: 'Auto', createdAt: new Date().toLocaleString() }, ...items]); setMeetTitle(''); setNotice('Google Meet room created.'); };
  const modeMeta = useMemo(() => modes.find((item) => item.key === activeMode) || modes[1], [activeMode]);

  if (mode === 'wallet') return <><PageHeader eyebrow="TOKEN WALLET · ALL ROLES" title="Fuel your learning" description="Use HELIX tokens for AI practice, adaptive reviews and premium assessments." actions={<div className="token-balance"><Coins size={19} /><strong>{tokenBalance}</strong><span>tokens</span></div>} /><section className="experience-hero experience-hero--wallet"><div><span className="eyebrow">LEARN WITHOUT FRICTION</span><h2>Small top-ups.<br /><em>Big momentum.</em></h2><p>Your balance is shared across AI Practice and Tests. Every activity shows its cost before you start.</p></div><div className="token-orbit"><Coins size={42} /><strong>{tokenBalance}</strong><span>available tokens</span></div></section><Section title="Choose a token pack" description="Demo checkout is stored locally. Connect your payment provider when the backend is ready."><div className="token-pack-grid">{[{ amount: 100, price: '₫49,000', popular: false }, { amount: 300, price: '₫119,000', popular: true }, { amount: 700, price: '₫249,000', popular: false }].map((pack) => <article key={pack.amount} className={pack.popular ? 'is-popular' : ''}>{pack.popular ? <span className="token-popular">Most popular</span> : null}<Coins size={24} /><strong>{pack.amount}</strong><span>tokens</span><b>{pack.price}</b><Button onClick={() => buy(pack.amount, pack.price)}>Add tokens</Button></article>)}</div></Section><Section title="Usage history"><div className="usage-list"><div><span>AI Speaking practice</span><b>-5 tokens</b><small>Today · 09:42</small></div><div><span>A2 progress check</span><b>-12 tokens</b><small>Yesterday · 18:10</small></div><div><span>Token top-up</span><b className="text-success">+300 tokens</b><small>12/07/2026</small></div></div></Section>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;

  if (mode === 'assessments') return <><PageHeader eyebrow="TESTS & REVIEW · STUDENT" title="Know your next level" description="Take a placement test, revisit weak skills and turn mistakes into progress." actions={<Button icon={Sparkles} onClick={() => setNotice('Adaptive review plan generated from your latest results.')}>Build review plan</Button>} /><div className="assessment-hero"><div><span className="eyebrow">YOUR LEARNING SIGNAL</span><h2>A2 is getting stronger.</h2><p>Based on 42 practice answers, your next focus is speaking fluency and past-tense questions.</p><div className="assessment-hero__stats"><span><strong>68%</strong><small>estimated mastery</small></span><span><strong>3</strong><small>skills to review</small></span><span><strong>12</strong><small>tokens for next test</small></span></div></div><div className="target-ring"><div><strong>A2</strong><span>current level</span></div></div></div><Section title="Tests and assessments"><div className="assessment-grid">{tests.map((test) => <article key={test.id}><div className="assessment-card__top"><StatusBadge status={test.status} /><span>{test.kind}</span></div><h3>{test.title}</h3><p><Clock3 size={15} />{test.duration} · {test.level}</p><Button variant={test.id === 'placement' ? 'primary' : 'secondary'} onClick={() => { update('assessments', (items = tests) => items.map((item) => item.id === test.id ? { ...item, status: 'In progress' } : item)); setNotice(`${test.title} is ready. 12 tokens reserved.`); }}>{test.status === 'Not started' ? 'Start test' : 'Continue' } <ArrowRight size={16} /></Button></article>)}</div></Section><Section title="Mistakes to revisit" description="HELIX remembers the patterns you want to improve. Review them until they disappear."><div className="mistake-grid">{mistakes.map((mistake) => <article key={mistake.id}><div><span className="mistake-icon"><RefreshCw size={17} /></span><StatusBadge status={mistake.skill} /></div><h3>{mistake.title}</h3><p>{mistake.detail}</p><footer><span>{mistake.count} attempts to revisit</span><button type="button" onClick={() => retry(mistake)}>Practice again <ChevronRight size={15} /></button></footer></article>)}</div></Section>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;

  if (mode === 'meet') return <><PageHeader eyebrow="MEET & ATTENDANCE · MENTOR" title="Meet without the admin work" description="Create a room, invite the class and let HELIX record check-in and check-out automatically." actions={<div className="live-pill"><i />Auto attendance is on</div>} /><section className="meet-hero"><div><span className="eyebrow">CONNECTED CLASSROOM</span><h2>One link.<br /><em>Every signal.</em></h2><p>HELIX opens Google Meet in a new tab and keeps attendance status in sync with the session timeline.</p><div className="meet-hero__flow"><span><b>01</b>Create room</span><ArrowRight size={16} /><span><b>02</b>Join class</span><ArrowRight size={16} /><span><b>03</b>Auto check-out</span></div></div><div className="meet-hero__visual"><Video size={34} /><strong>Live classroom</strong><span>check-in starts 15 min before class</span><div className="meet-hero__avatars"><i>MA</i><i>HN</i><i>TH</i><b>+21</b></div></div></section><div className="meet-grid"><Section title="Create a Google Meet room" description="The room link is generated for this demo and can be replaced by the Google Calendar API."><div className="form-stack"><Field label="Session title" required><input value={meetTitle} onChange={(e) => setMeetTitle(e.target.value)} placeholder="A2-01 · Unit 7 · Speaking practice" /></Field><div className="form-grid"><Field label="Start"><input type="datetime-local" defaultValue="2026-07-16T19:00" /></Field><Field label="Duration"><select defaultValue="90"><option value="90">90 minutes</option><option value="60">60 minutes</option></select></Field></div><label className="switch-row"><span><strong>Automatic check-in/out</strong><small>Check in when a learner joins Meet and check out when they leave.</small></span><input type="checkbox" defaultChecked /></label><Button icon={Video} disabled={!meetTitle.trim()} onClick={createMeet}>Create Meet room</Button></div></Section><Section title="Attendance timeline"><div className="attendance-timeline"><div className="is-live"><span><i /></span><div><strong>Unit 6 · Giving directions</strong><small>Live now · 19:00–20:30</small></div><StatusBadge status="Auto tracking" /></div><div><span><Check size={15} /></span><div><strong>12 learners checked in</strong><small>Average join time · 18:57</small></div><b>12/24</b></div><div><span><Clock3 size={15} /></span><div><strong>Next auto check-out</strong><small>At 20:30 or when the learner leaves</small></div><b>20:30</b></div></div></Section></div>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;

  return <><PageHeader eyebrow="AI PRACTICE · STUDENT" title="Practice with HELIX AI" description="Listen, speak, read and write in focused sessions that remember where you struggle." actions={<div className="token-balance"><Coins size={18} /><strong>{tokenBalance}</strong><span>tokens</span></div>} /><section className="ai-hero"><div className="ai-hero__copy"><span className="eyebrow">YOUR PERSONAL PRACTICE ROOM</span><h2>Turn mistakes<br /><em>into muscle memory.</em></h2><p>Every session adapts to your level. Every mistake becomes a small, replayable lesson.</p><div className="ai-hero__actions"><Button icon={Play} onClick={startPractice} disabled={running || tokenBalance < 5}>{running ? 'Starting session…' : `Start ${modeMeta.label} · 5 tokens`}</Button><span><Sparkles size={15} /> AI coach ready</span></div></div><div className="ai-hero__orb"><BrainCircuit size={42} /><span>HELIX</span><strong>adaptive<br />practice</strong><i /><i /><i /></div></section><Section title="Choose a skill" description="Short sessions. Clear feedback. Visible progress."><div className="skill-grid">{modes.map((item) => { const Icon = item.icon; return <button type="button" key={item.key} className={`skill-card skill-card--${item.color} ${activeMode === item.key ? 'is-active' : ''}`} onClick={() => setActiveMode(item.key)}><span className="skill-card__icon"><Icon size={24} /></span><span><strong>{item.label}</strong><small>{item.copy}</small></span><ChevronRight size={18} /></button>; })}</div></Section><div className="dashboard-grid dashboard-grid--wide"><Section title="Your recurring mistakes" actions={<button type="button" className="section-link" onClick={() => setNotice('All mistakes are shown in Tests & Review.')}>View all <ArrowRight size={15} /></button>}><div className="mistake-list">{mistakes.map((mistake) => <div key={mistake.id}><span className="mistake-icon"><RefreshCw size={16} /></span><span><strong>{mistake.title}</strong><small>{mistake.detail}</small></span><b>{mistake.count}</b><button type="button" onClick={() => retry(mistake)} aria-label={`Review ${mistake.title}`}><ChevronRight size={17} /></button></div>)}</div></Section><Section title="Session recipe"><div className="recipe-card"><span className="recipe-card__label">{modeMeta.label.toUpperCase()} · BEGINNER+</span><h3>Directions in real life</h3><p>6 prompts · 8 minutes · instant feedback</p><div><span>Vocabulary</span><span>Fluency</span><span>Accuracy</span></div><Button variant="secondary" onClick={startPractice} disabled={running || tokenBalance < 5}>Preview session</Button></div></Section></div>{notice ? <Toast onClose={() => setNotice('')}>{notice}</Toast> : null}</>;
}
