import React, { useState } from 'react';
import { Eye, EyeOff, LockKeyhole, Mail } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import AuthLayout from '../../layouts/AuthLayout';
import { Button, Field, InlineNotice } from '../../components/UI';

export default function LoginPage() {
  const navigate = useNavigate(); const [email, setEmail] = useState('student@hope.edu.vn'); const [password, setPassword] = useState('Hope@2026'); const [show, setShow] = useState(false); const [role, setRole] = useState('student'); const [loading, setLoading] = useState(false);
  const submit = (e) => { e.preventDefault(); setLoading(true); window.setTimeout(() => navigate(`/${role}`), 450); };
  return <AuthLayout centered><div className="auth-form-header"><span className="screen-code">SH-01 · HELIX ACCESS</span><h2>Sign in to HELIX</h2><p>Use your Hope School account to continue.</p></div><form className="auth-form" onSubmit={submit}><Field label="Email" required><div className="input-with-icon"><Mail size={18} /><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" /></div></Field><Field label="Password" required><div className="input-with-icon"><LockKeyhole size={18} /><input type={show ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></Field><div className="auth-form__row"><label className="checkbox"><input type="checkbox" defaultChecked /><span>Remember me</span></label><Link to="/forgot-password">Forgot password?</Link></div><Field label="Demo role"><select value={role} onChange={(e) => setRole(e.target.value)}><option value="student">Student</option><option value="mentor">Mentor / Instructor</option><option value="coordinator">Coordinator</option><option value="admin">Administrator</option></select></Field><Button type="submit" className="button--full" disabled={!email || !password || loading}>{loading ? 'Signing in…' : 'Sign in'}</Button></form><InlineNotice title="Product preview">Choose a role to explore the full 29-screen MVP workspace.</InlineNotice><p className="auth-help">Need help? Contact Hope School operations.</p></AuthLayout>;
}
